# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_woollyuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='woollyuser',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.WoollyUserType'),
            preserve_default=False,
        ),
    ]
