# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170518_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woollyusertype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
