# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170519_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationmember',
            name='association',
        ),
    ]
