# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_associationmember'),
        ('core', '0011_auto_20170526_0948'),
    ]

    operations = [
    ]
