# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_woollyuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='core.OrderLine', to='core.Item'),
        ),
    ]
