# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', through='core.OrderLine', to='core.Item'),
        ),
    ]
