# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170518_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woollyuser',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WoollyUserType'),
        ),
        migrations.AlterField(
            model_name='woollyusertype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
