# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170518_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='woollyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='woollyuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='woollyuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='woollyuser',
            name='type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.WoollyUserType'),
        ),
    ]
