# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170601_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_group',
        ),
        migrations.RemoveField(
            model_name='itemspecifications',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemspecifications',
            name='woolly_user_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='association',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_methods',
        ),
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='AssociationMember',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemGroup',
        ),
        migrations.DeleteModel(
            name='ItemSpecifications',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='WoollyUserType',
        ),
    ]
