# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='max_article_quantity',
            new_name='max_item_quantity',
        ),
    ]
