# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170522_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
            preserve_default=False,
        ),
    ]
