# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_item_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_group',
            new_name='group',
        ),
    ]
