# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20170522_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.DeleteModel(
            name='ItemGroup',
        ),
    ]
