# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20170522_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspecifications',
            name='woolly_user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.WoollyUserType'),
        ),
    ]
