# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20170609_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_methods',
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_methods',
            field=models.ManyToManyField(to='sales.PaymentMethod'),
        ),
    ]
