# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_auto_20170609_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('rights', models.CharField(max_length=50)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sales.Association')),
                ('woollyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
