# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20170524_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.Association'),
        ),
    ]
