# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20170524_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='itemspecifications',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='sales.Item'),
        ),
    ]
