# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20170526_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='association',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.Association'),
        ),
    ]
