# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20170615_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='payment_methods',
            new_name='paymentmethods',
        ),
    ]
