# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_order_orderline_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemspecifications',
            name='woolly_user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='authentication.WoollyUserType'),
        ),
        migrations.DeleteModel(
            name='WoollyUserType',
        ),
    ]
