# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20170616_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmember',
            name='woollyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associationmembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
