# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170609_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woollyuser',
            old_name='type',
            new_name='woollyusertype',
        ),
    ]
