# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20170616_1450'),
        ('authentication', '0003_auto_20170616_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='woollyuser',
            name='associations',
            field=models.ManyToManyField(through='sales.AssociationMember', to='sales.Association'),
        ),
    ]
