# Generated by Django 2.0.3 on 2018-06-03 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fun_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('rights', models.CharField(max_length=50)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associationmembers', to='sales.Association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associationmembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=1000)),
                ('default', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('nemopay_id', models.CharField(max_length=30, null=True)),
                ('max_per_user', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editable', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemfields', to='sales.Field')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemfields', to='sales.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(sales.models.OrderStatus(0), 0), (sales.models.OrderStatus(1), 1), (sales.models.OrderStatus(2), 2), (sales.models.OrderStatus(3), 3), (sales.models.OrderStatus(4), 4), (sales.models.OrderStatus(5), 5), (sales.models.OrderStatus(6), 6)], default=sales.models.OrderStatus(0))),
                ('tra_id', models.IntegerField(default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='sales.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='sales.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='sales.Field')),
                ('orderline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='sales.OrderLine')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('begin_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('max_item_quantity', models.IntegerField()),
                ('max_payment_date', models.DateTimeField()),
                ('association', models.ForeignKey(on_delete=None, related_name='sales', to='sales.Association')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sales.ItemGroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='item',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.UserType'),
        ),
        migrations.AddField(
            model_name='field',
            name='items',
            field=models.ManyToManyField(through='sales.ItemField', to='sales.Item'),
        ),
        migrations.AddField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(through='sales.AssociationMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
