# Generated by Django 2.0.3 on 2018-05-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
    ]
