# Generated by Django 2.0.3 on 2018-05-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sales.ItemGroup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.UserType'),
        ),
    ]
