# Generated by Django 2.0.3 on 2018-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180611_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('ONGOING', 0), ('AWAITING_VALIDATION', 1), ('VALIDATED', 2), ('NOT_PAID', 3), ('PAID', 4), ('EXPIRED', 5), ('CANCELLED', 6), ('CANCELLABLE_LIST', (3, 1)), ('NOT_CANCELLED_LIST', (1, 2, 3, 4)), ('BUYABLE_STATUS_LIST', (0, 1, 3)), ('VALIDATED_LIST', (2, 4))], default=0),
        ),
    ]
