# Generated by Django 2.0.3 on 2018-05-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20180529_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nemopay_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
