# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_orderline_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_line', to='sales.Item'),
            preserve_default=False,
        ),
    ]
