# Generated by Django 2.1.7 on 2019-03-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20180731_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='associationmember',
            options={'ordering': ('id',), 'verbose_name': 'Association Member'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='itemfield',
            options={'ordering': ('id',), 'verbose_name': 'Item Field'},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'ordering': ('id',), 'verbose_name': 'Item Group'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ('id',), 'verbose_name': 'Order Line'},
        ),
        migrations.AlterModelOptions(
            name='orderlinefield',
            options={'ordering': ('id',), 'verbose_name': 'OrderLine Field'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ('id',), 'verbose_name': 'OrderLine Item'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='field',
            name='default',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sales.ItemGroup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_per_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nemopay_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemfields', to='sales.Field'),
        ),
        migrations.AlterField(
            model_name='itemfield',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemfields', to='sales.Item'),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='max_per_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.Sale'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ONGOING'), (1, 'AWAITING_VALIDATION'), (2, 'VALIDATED'), (3, 'NOT_PAID'), (4, 'PAID'), (5, 'EXPIRED'), (6, 'CANCELLED')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tra_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='sales.Item'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='sales.Order'),
        ),
        migrations.AlterField(
            model_name='orderlinefield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlinefields', to='sales.Field'),
        ),
        migrations.AlterField(
            model_name='orderlinefield',
            name='orderlineitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlinefields', to='sales.OrderLineItem'),
        ),
        migrations.AlterField(
            model_name='orderlinefield',
            name='value',
            field=models.CharField(blank=True, editable='isEditable', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='orderline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlineitems', to='sales.OrderLine'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='association',
            field=models.ForeignKey(on_delete=None, related_name='sales', to='sales.Association'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='max_item_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
