# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_orderline_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='members',
            field=models.ManyToManyField(through='sales.OrderLine', to='sales.Item'),
        ),
    ]
