# Generated by Django 2.2.3 on 2019-08-05 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190312_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationmember',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='itemfield',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderlinefield',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.Sale'),
        ),
    ]
