# Generated by Django 2.2.3 on 2019-08-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190805_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='association',
            name='members',
        ),
        migrations.AlterField(
            model_name='association',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='AssociationMember',
        ),
    ]
