# Generated by Django 2.2.3 on 2019-08-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20190811_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='fun_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
