# Generated by Django 2.2.3 on 2019-08-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20190811_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ('shortname',)},
        ),
        migrations.RenameField(
            model_name='association',
            old_name='name',
            new_name='shortname',
        ),
    ]
