# Generated by Django 2.2.3 on 2019-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20190811_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='max_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='max_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='max_item_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
