# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='api_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
