# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20170609_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_methods',
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_methods',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.PaymentMethod'),
            preserve_default=False,
        ),
    ]
